-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 14:46:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sp_kiv_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lrunt_pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lrunt_pravo` ;

CREATE TABLE IF NOT EXISTS `lrunt_pravo` (
  `id_pravo` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(30) NOT NULL,
  `vaha` INT NOT NULL,
  PRIMARY KEY (`id_pravo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lrunt_uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lrunt_uzivatel` ;

CREATE TABLE IF NOT EXISTS `lrunt_uzivatel` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `id_pravo` INT NOT NULL DEFAULT 3,
  `username` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(50) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_uzivatel`),
  INDEX `fk_uzivatel_pravo_idx` (`id_pravo` ASC),
  CONSTRAINT `fk_uzivatel_pravo`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `lrunt_pravo` (`id_pravo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lrunt_produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lrunt_produkt` ;

CREATE TABLE IF NOT EXISTS `lrunt_produkt` (
  `id_produkt` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) CHARACTER SET 'ascii' NOT NULL,
  `cena` INT NOT NULL,
  `mnozstvi` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_produkt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lrunt_recenze`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lrunt_recenze` ;

CREATE TABLE IF NOT EXISTS `lrunt_recenze` (
  `id_recenze` INT NOT NULL AUTO_INCREMENT,
  `id_uzivatel` INT NOT NULL,
  `id_produkt` INT NOT NULL,
  `pocet_hvezd` INT NOT NULL,
  `zverejneno` TINYINT NOT NULL,
  `popis` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_recenze`),
  INDEX `fk_recenze_uzivatel_idx` (`id_uzivatel` ASC),
  INDEX `fk_recenze_produkt_idx` (`id_produkt` ASC),
  CONSTRAINT `fk_recenze_uzivatel`
    FOREIGN KEY (`id_uzivatel`)
    REFERENCES `lrunt_uzivatel` (`id_uzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recenze_produkt`
    FOREIGN KEY (`id_produkt`)
    REFERENCES `lrunt_produkt` (`id_produkt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `lrunt_pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `lrunt_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (1, 'Super Admin', 20);
INSERT INTO `lrunt_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (2, 'Admin', 10);
INSERT INTO `lrunt_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (3, 'Recenzent', 5);
INSERT INTO `lrunt_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (4, 'Autor', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `lrunt_uzivatel`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `lrunt_uzivatel` (`id_uzivatel`, `id_pravo`, `username`, `heslo`, `email`) VALUES (1, 1, 'lrunt', '#J3b2T0', 'lukas.runt@gmail.com');
INSERT INTO `lrunt_uzivatel` (`id_uzivatel`, `id_pravo`, `username`, `heslo`, `email`) VALUES (2, 2, 'admin', '#J7J23mA0m1n', 'adminadmin@gmail.com');
INSERT INTO `lrunt_uzivatel` (`id_uzivatel`, `id_pravo`, `username`, `heslo`, `email`) VALUES (3, 3, 'recenzent', 'JaJsemRecenzent', 'recenzent@gmail.com');
INSERT INTO `lrunt_uzivatel` (`id_uzivatel`, `id_pravo`, `username`, `heslo`, `email`) VALUES (4, 4, 'autor', 'JaJsemAutor', 'autor.autor@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lrunt_produkt`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `lrunt_produkt` (`id_produkt`, `nazev`, `cena`, `mnozstvi`) VALUES (1, 'Smažený sýr, hranolky, tatarská omáčka', 70, '100g');

COMMIT;


-- -----------------------------------------------------
-- Data for table `lrunt_recenze`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `lrunt_recenze` (`id_recenze`, `id_uzivatel`, `id_produkt`, `pocet_hvezd`, `zverejneno`, `popis`) VALUES (1, 3, 1, 5, DEFAULT, 'Vynikajici');

COMMIT;

